config/routes.rb
Rails.application.routes.draw do
  namespace :mypage do
    get 'accounts/edit'
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  root "static_pages#top"
  get "/complete_signup", to: "static_pages#complete_signup"
  get "/terms", to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"
  delete '/logout', to: 'sessions#destroy'

  resources :quizzes, only: [:index] do
    resource 'random_exam', on: :member, module: 'quizzes', only: %w[show]
    resource 'bookmarked_exam', on: :member, module: 'quizzes', only: %w[show]
    resource 'bookmark', on: :member, module: 'quizzes', only: %w[create destroy]
  end

  namespace 'quizzes' do
    delete 'random_exam', to: 'random_exams#destroy'
    delete 'bookmarked_exam', to: 'bookmarked_exams#destroy'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  namespace 'mypage' do
    root to: 'quizzes#index'
    resources :quizzes, only: %w[index]
    resource :line_notification, only: %w[edit update]
    resource :account, only: %w[edit]
  end

  resources :users, only: %w[destroy]

  match '*path', to: 'application#render404', via: :all
end

app/views/shared/_require_bookmark_modal.html.erb
<dialog id="require_bookmark_modal" class="modal">
  <div class="modal-box flex justify-center">
    <div>
      <h3 class="text-lg font-bold flex justify-center">
        マイクイズ帳が真っ白です…😢
      </h3>
      <p class="py-4 leading-relaxed">
        マイクイズ帳からランダムで出題することができます。<br>
        ・苦手クイズ<br>
        ・記憶済クイズ etc...<br>
        集中して学習したいクイズをマイクイズに追加してみましょう。<br>
      </p>
      <hr>
      <div class="max-w-lg w-full mt-6">
        <%= link_to 'ランダム出題', quiz_random_exam_path(Quiz.get_random_quiz(session)), class: 'btn btn-primary w-full' %>
        <%= link_to 'クイズ一覧', quizzes_path, class: 'btn btn-primary w-full mt-3' %>
      </div>
    </div>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/shared/_require_login_modal.html.erb
<dialog id="require_login_modal" class="modal">
  <div class="modal-box flex justify-center">
    <div>
      <h3 class="text-lg font-bold flex justify-center">
      <span class="font-bold underline decoration-green-500 decoration-4 underline-offset-0">
        LINE連携
      </span>
        で苦手問題を克服🤩
      </h3>
      <p class="py-4 leading-relaxed">
        LINE連携により以下の機能を利用できます。<br>
        <br>
        ✅ 苦手クイズをマイクイズ帳に登録<br>
        ✅ マイクイズ帳からランダム出題し集中練習<br>
        ✅ クイズのデイリー通知<br>
      </p>
      <%= link_to auth_at_provider_path(provider: :line), class: 'btn btn-sm bg-green-500 text-white flex justify-center' do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-line" viewBox="0 0 16 16">
          <path d="M8 0c4.411 0 8 2.912 8 6.492 0 1.433-.555 2.723-1.715 3.994-1.678 1.932-5.431 4.285-6.285 4.645-.83.35-.734-.197-.696-.413l.003-.018.114-.685c.027-.204.055-.521-.026-.723-.09-.223-.444-.339-.704-.395C2.846 12.39 0 9.701 0 6.492 0 2.912 3.59 0 8 0ZM5.022 7.686H3.497V4.918a.156.156 0 0 0-.155-.156H2.78a.156.156 0 0 0-.156.156v3.486c0 .041.017.08.044.107v.001l.002.002.002.002a.154.154 0 0 0 .108.043h2.242c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157Zm.791-2.924a.156.156 0 0 0-.156.156v3.486c0 .086.07.155.156.155h.562c.086 0 .155-.07.155-.155V4.918a.156.156 0 0 0-.155-.156h-.562Zm3.863 0a.156.156 0 0 0-.156.156v2.07L7.923 4.832a.17.17 0 0 0-.013-.015v-.001a.139.139 0 0 0-.01-.01l-.003-.003a.092.092 0 0 0-.011-.009h-.001L7.88 4.79l-.003-.002a.029.029 0 0 0-.005-.003l-.008-.005h-.002l-.003-.002-.01-.004-.004-.002a.093.093 0 0 0-.01-.003h-.002l-.003-.001-.009-.002h-.006l-.003-.001h-.004l-.002-.001h-.574a.156.156 0 0 0-.156.155v3.486c0 .086.07.155.156.155h.56c.087 0 .157-.07.157-.155v-2.07l1.6 2.16a.154.154 0 0 0 .039.038l.001.001.01.006.004.002a.066.066 0 0 0 .008.004l.007.003.005.002a.168.168 0 0 0 .01.003h.003a.155.155 0 0 0 .04.006h.56c.087 0 .157-.07.157-.155V4.918a.156.156 0 0 0-.156-.156h-.561Zm3.815.717v-.56a.156.156 0 0 0-.155-.157h-2.242a.155.155 0 0 0-.108.044h-.001l-.001.002-.002.003a.155.155 0 0 0-.044.107v3.486c0 .041.017.08.044.107l.002.003.002.002a.155.155 0 0 0 .108.043h2.242c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157H11.81v-.589h1.525c.086 0 .155-.07.155-.156v-.56a.156.156 0 0 0-.155-.157H11.81v-.589h1.525c.086 0 .155-.07.155-.156Z" />
        </svg>
        LINE連携
      <% end %>
    </div>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/shared/_toasts.html.erb
<div id="flash_messages" class="toast toast-end">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> flex justify-between items-center">
      <span><%= message %></span>
      <button class="ml-4" onclick="this.parentElement.style.display='none';">X</button>
    </div>
  <% end %>
</div>