config/routes.rb
Rails.application.routes.draw do
  namespace :mypage do
    get 'accounts/edit'
  end
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  root "static_pages#top"
  get "/complete_signup", to: "static_pages#complete_signup"
  get "/terms", to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"
  delete '/logout', to: 'sessions#destroy'

  resources :quizzes, only: [:index] do
    resource 'random_exam', on: :member, module: 'quizzes', only: %w[show]
    resource 'bookmarked_exam', on: :member, module: 'quizzes', only: %w[show]
    resource 'bookmark', on: :member, module: 'quizzes', only: %w[create destroy]
  end

  namespace 'quizzes' do
    delete 'random_exam', to: 'random_exams#destroy'
    delete 'bookmarked_exam', to: 'bookmarked_exams#destroy'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  namespace 'mypage' do
    root to: 'quizzes#index'
    resources :quizzes, only: %w[index]
    resource :line_notification, only: %w[edit update]
    resource :account, only: %w[edit]
  end

  resources :users, only: %w[destroy]

  match '*path', to: 'application#render404', via: :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static_pages/layouts/application'

  def top
    @sample_quiz = Quiz.all.sample
  end

  def complete_signup; end

  def terms; end

  def privacy; end
end

app/views/static_pages/layouts/_footer.html.erb
<footer class="footer footer-center bg-neutral text-neutral-content rounded p-10">
  <nav class="grid grid-flow-col gap-4">
    <%= link_to '利用規約', terms_path, class: 'link link-hover' %>
    <%= link_to 'プライバシーポリシー', privacy_path, class: 'link link-hover' %>
  </nav>
  <aside>
    <p>Copyright © BetaMaster - All right reserved by BetaMaster</p>
  </aside>
</footer>

app/views/static_pages/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'shared/require_login_modal' %>
    <%= render 'shared/require_bookmark_modal' %>
    <%= render 'shared/toasts' %>
    <%= render 'static_pages/layouts/footer' %>
  </body>
</html>